### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-fedramp-dashboard#113]
Will Vendors be able to submit questions once the solicitation is released?

**Comment by randyhart** [comment]
@cotopaxisummit 
Per the RFQ posted to e-Buy last night (and copied to GitHub just now):

Questions or comments regarding this RFQ shall be submitted as issues within the BPA GitHuB repository at https://github.com/18F/bpa-fedramp-dashboard no later than April 1, 2016 at 6:00 PM (PST), to allow the Government sufficient time to respond
