### ISSUE TITLE
Template and sample FedRAMP data

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#114]
> Contractor shall build a static public site that will provide client-side rendering of the dashboard (preferably via JavaScript), based on a flat file (csv/json) accessible through the GitHub Application Program Interface (API). A template of the data format of the data can be found in this Github Repository and sample data is available here. The static-site must be deployable through a single bash command. All files will be stored statically (server-side) and all dynamic interaction will be enabled in the browser (client-side).

The PWS seems to indicate that a the data format and a sample flat file is available for our review now.  However, I am unable to locate this repository in any of the RFQ documents.  Please provide a hyperlink with a representative flat file.  If this flat file is not representative of the data size, please provide some guidance on the order of magnitude of the size of the file (i.e. number of rows).

**Comment by jposi** [comment]
The flat file of the sample data is available here: https://github.com/18F/fedramp-micropurchase/blob/test-pr/data/03-21-2016.json
