### ISSUE TITLE
Please describe what is meant by "Contractor Arrival & Acclimation"

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#12]
In the Instructions For Oral Presentations, it would be helpful to have a brief description (1-2 sentences) letting us know what is meant by Contractor Arrival and Acclimation.

**Comment by jposi** [comment]
We have scheduled 5 minutes for a contractor to get settled in the room - e.g. remove jackets, get notebook and pen, etc.
