### ISSUE TITLE
Easier auditing and compliance self-checking?

### ISSUE THREAD

**Issue by SWortham** [18F/bpa-fedramp-dashboard#120]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Steve Wortham - Software Engineer for Asynchrony

## Section of RFQ documents
Draft_PWS.md - 2.0 Objectives

## Question/Comment
My question is about the item under objectives that says, "Easier auditing and compliance self-checking". 

What does this mean? Is this for members of the CSPs to be able to easily look themselves up and check their status within the compliance/certification process? That was my first thought, but I could be completely off so I wanted to ask. Thanks for your time.

**Comment by jposi** [comment]
Yes, your interpretation is correct.
