### ISSUE TITLE
Number of views

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-fedramp-dashboard#121]
# Question/Comment on FedRamp Dashboard RFQ

## Section 4, bullet 3 of RFQ documents
States that “Contractor shall review user research and conduct additional user research in order to provide data views that are most useful.” 

## Question/Comment
If we assume that the outcome of the research recommends 2 views for costing purposes, how can a FFP contract accommodate the additional effort if the outcome of the research is 10 views? You might consider a phased approach that re-costs the effort after these basic criteria have been established.

**Comment by jposi** [comment]
In section 5.7.3 of the PWS we have articulated that this project will likely require no more than 4-5 personnel, based on our internal research and understanding of the complexity of the data. We commit to providing key users to develop high priority user stories. We anticipate that your work with them and with the Product Owner will provide guidance about the number and prioritization of views needed.
