### ISSUE TITLE
How familiar is the FedRamp product owner with the Agile methodology? 

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-fedramp-dashboard#122]
Question/Comment on FedRamp Dashboard RFQ

Name and affiliation
Todd Hutchison – PwC Contracts Manager

Section of RFQ documents
GOVERNMENT ROLES AND RESPONSIBILITIES FOR FEDRAMP DASHBOARD PLATFORM SUPPORT – Product Owner

Question/Comment
How familiar is the FedRamp product owner with the Agile methodology?  Will the development of the dashboard be the product owner's primary responsibility during the 60 day project duration?

**Comment by jposi** [comment]
Apologies for the delay on this answer. The FedRAMP and 18F team are familiar with agile methodology. The FedRAMP and 18F team will have resources dedicated to this project in order to facilitate the project completion within the timeframes defined in the RFQ.
