### ISSUE TITLE
Technical Acceptance and Evaluation

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-fedramp-dashboard#123]
Question/Comment on FedRamp Dashboard RFQ

Name and affiliation
Todd Hutchison – PwC Contracts Manager

Section of RFQ documents
Draft_PWS.md - 5.6.2 Inspection and Acceptance of Services

Question/Comment
Who will the product owner and COR be working with from a technical perspective on the Government side to evaluate and accept the code?

**Comment by randyhart** [comment]
As the Government roles sheet suggests https://github.com/18F/bpa-fedramp-dashboard/blob/master/Posted-to-eBuy/GovernmentRolesandResponsibilities.md , the Product Owner and COR will be working with the 18F Product Manager to evaluate and accept the code. The PM may work with a developer on 18F's team to evaluate the code as well.
