### ISSUE TITLE
Are there any particular frameworks or libraries that the front end should be built in?

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-fedramp-dashboard#124]
Question/Comment on FedRamp Dashboard RFQ

Name and affiliation
Todd Hutchison – PwC Contracts Manager

Section of RFQ documents
Draft_PWS.md – 4.0 Requirements

Question/Comment
Are there any particular frameworks or libraries that the front end should be built in?

**Comment by randyhart** [comment]
No. The libraries and frameworks are at the offerors' discretion as long as they also comply with the PWS requirements (i.e. the end result must comply with the US Web Design Standards, etc.)
