### ISSUE TITLE
Conflicting times for submission due date

### ISSUE THREAD

**Issue by Agile-David** [18F/bpa-fedramp-dashboard#125]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
David Tilghman - Senior Vice President, TrueTandem LLC

## Section of RFQ documents
RFQ Page 1 and eBuy Site

## Question/Comment
Please clarify the time that our responses are due on April 8th.  The RFQ states the time as 1PM Pacific Time (4PM EST) while the eBuy site states 7PM EST.  Which is correct?

**Comment by markmohler** [comment]
Hi David, 
There was a modification posted yesterday to clarify this. The eBuy date/time of 8 April, 7pm EDT is the correct time. The revised RFQ reflecting this change is posted under document "ID09160019 RFQ revised 03312016." 
Thanks!

**Comment by Agile-David** [comment]
Understood.  Thanks Mark!
