### ISSUE TITLE
Orals Presentation Location

### ISSUE THREAD

**Issue by ISTF159** [18F/bpa-fedramp-dashboard#126]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Izabela Stani, Contracts Administrator, TechFlow, Inc.

## Section of RFQ documents
Instructions for Oral Presentations, Part Two / Location / Page 2

## Question/Comment
Please confirm that Contractor Oral Presentations will be conducted both via in-person interviews and video chat, as opposed to one over the other.  Please see below excerpt for reference:

_Location The oral presentations shall be held in Washington, DC and via video chat. Any travel expenses associated with attending the orals are the responsibility of the contractor. If the contractor chooses to Interview in person, location information will be provided upon invitation._

**Comment by jposi** [comment]
That is correct. We will have staff in person and via video, and anticipate that some contractors may have the same. Either in person, via remote means, or a combination of both would all be acceptable ways to participate in the oral presentation.
