### ISSUE TITLE
Background Investigations

### ISSUE THREAD

**Issue by TiaraI** [18F/bpa-fedramp-dashboard#128]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Tiara Isom, Acumen Solutions

## Section of RFQ documents
N/A

## Question/Comment
We kindly request that 18F confirm that there are no background investigation or citizenship requirements for personnel supporting the proposed services beyond US employment eligibility.

**Comment by jposi** [comment]
That is correct.
