### ISSUE TITLE
Inspection and Acceptance Period

### ISSUE THREAD

**Issue by TiaraI** [18F/bpa-fedramp-dashboard#129]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Tiara Isom, Acumen Solutions

## Section of RFQ documents
Section 4.1 Requirements and Section 5.6.2. Inspection and Acceptance 

## Question/Comment
Upon further review, because of the brevity of sprints, and the following details contained within Section 4.1 Requirements "As part of this being purchased off of the Agile Blanket Purchase Agreement (BPA), work will be conducted in two week sprints and reviewed at the end of each sprint for acceptability before moving on," we kindly request that the Inspection and Acceptance period be shortened from 10 days to 2 business days such that Section 5.6.2. Inspection and Acceptance of Services in the PWS reads  "All periodic reports and task deliverables shall be inspected, tested (where applicable), reviewed, and accepted by the Government within 2 business days of the conclusion of each sprint."

**Comment by patrickmcconnell** [comment]
Name and affiliation: Patrick McConnell, CTO of SemanticBits

We agree with this request and second it.

**Comment by jposi** [comment]
We appreciate this suggestion. Upon further review we will amend Section 5.6.2 to say 5 days, rather than 2, in order to accommodate internal workflow. We hope to respond more quickly than that, but will have a 5 day limit on our turnaround time. The PWS will be edited to reflect that change.
