### ISSUE TITLE
Logistics for Contractor Provided Questions

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#13]
In the Instructions For Oral Presentations, it would be helpful to know whether during "Contractor Provided Questions", will the government reviewers be in the room as we discuss our approach?  This would help us strategize our approach.

**Comment by jposi** [comment]
Yes, the technical evaluators will participate in the oral presentations but only the Contracting Officer/Specialist will ask questions. The oral presentations instructions will be revised to reflect that.

**Comment by patrickmcconnell** [comment]
@jposi the question is about the time during which we will be given the questions to ponder and when they will be asked.

**Comment by randyhart** [comment]
@patrickmcconnell 
Per the Instructions for Oral Presentations, our initial draft anticipated providing the interview questions 10 minutes prior to the beginning of the Oral Presentations.  We are going to adjust this language in the final documents - we will provide the questions via e-mail to the Offerors one hour prior to their scheduled Oral Presentation.  This hour should be adequate for Offerors to strategize on which of their members will be the lead for responding to each question.

**Comment by patrickmcconnell** [comment]
OK - thanks @randyhart .
