### ISSUE TITLE
QASP Inspection Results Will Not Be Made Public?

### ISSUE THREAD

**Issue by TiaraI** [18F/bpa-fedramp-dashboard#130]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Tiara Isom, Acumen Solutions

## Section of RFQ documents
QASP under the Procedures section

## Question/Comment
In the "Procedures" section of the QASP it states "Inspection results will be recorded in a via GitHub issue, noting the date, time, and result of inspection or verification."  We kindly request 18F to confirm that these results will be posted in a private repository.

**Comment by jposi** [comment]
Per Section 6.9 of the PWS and 18F's Transparency Policy: "During the performance of this task order, 18F will similarly publish source code, data related to project management (e.g., user stories, milestones, and performance metrics), and top-line spending data." Therefore, we anticipate that this work will be done in a public repository.
