### ISSUE TITLE
Warranties Regarding Open Source Technology Licenses

### ISSUE THREAD

**Issue by TiaraI** [18F/bpa-fedramp-dashboard#131]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Tiara Isom, Acumen Solutions

## Section of RFQ documents
6.10 of the PWS

## Question/Comment
During the pre-solicitation Q&As, 18F clarified that  “Per section 6.10 of the PWS, 18F intends to commit Deliverables under this order to the public domain" and that the Deliverables would be subject to the warranty terms of the associated open source technology license and that "no additional warranty provisions shall apply."  

In accordance with this explanation, we kindly request that the following statement be added to the solicitation:  "Deliverables provided under this TO with an open source technology license shall only be subject to such warranty provisions that are included in the open source technology's license terms, as referenced within the Deliverables.  The warranties stated in the open source technology license are the sole warranty obligations for the Contractor under this Task Order, and expressly exclude any applicable warranties under FAR part 52.246-4 and 52.246-6 and warranties of fitness for a particular purpose and warranties of merchantability."

**Comment by jposi** [comment]
The RFQ package does not include warranty provisions beyond those included in the CC0 license. We view the PWS's [Inspection & Acceptance provisions](https://github.com/18F/bpa-fedramp-dashboard/blob/master/Posted-to-eBuy/FinalPWS.md#562-inspection-and-acceptance-of-services), and our use of the [CC0 license](https://wiki.creativecommons.org/wiki/CC0_FAQ), as making any additional disclaimers unnecessary. The Inspection rights included in [FAR 52.246-4](http://farsite.hill.af.mil/reghtml/regs/far2afmcfars/fardfars/far/52_246.htm) do not conflict with this position. Thus the government will not add any additional disclaimers.
