### ISSUE TITLE
Revised Past Performance Sizing Requirements

### ISSUE THREAD

**Issue by sjfischr** [18F/bpa-fedramp-dashboard#138]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Steve Fischer, 18F Account Manager, Ventera Corporation 

## Section of RFQ documents

> Similar Size: Similar size includes projects utilizing up to six (6) Full Time Equivalent (FTE) staff on a project with a period of performance not exceeding three (3) months. **

The prior text of the RFQ stated the similar size to be: 

> “Recent, similar size, and technical scope are defined below: Similar Size: Similar size is equal to or greater than four (4) to five (5) Full Time Equivalent (FTE) staff having performed on project with a period of performance of two (2) months or more”. 

## Question/Comment
With these new stringent caps on size, an Offeror who may have two compliant public-facing dashboard past performances which met the original requirements would now be non-compliant, providing little, if any, time to locate and write suitable Past Performance entries under these new requirements. Please consider altering this language to be more inclusive per the original sizing rules of the RFQ.

**Comment by jposi** [comment]
Hello. Apologies for the delay. We will not be altering the RFQ at this time. Please continue with the instructions as they are posted.
