### ISSUE TITLE
Instructions For Oral Presentations FAR

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#15]
It would be helpful to know whether any FARs govern "Oral presentations" if this session is not governed by FAR 15.102.

**Comment by randyhart** [comment]
In accordance with Section 7.0 of  the Multiple Award Schedules (MAS) Desk Reference (http://www.gsa.gov/MASDESKTOP/index.htm), Contracting Officers may use oral presentations at their discretion. Agile BPA orders that utilize oral presentations are still governed by the ordering procedures of FAR Subpart 8.4.
