### ISSUE TITLE
Socio-economic categories

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#18]
I recall the government mentioning in a teleconference that agencies will have the option to designate socio-economic categories for their RFQs through the Agile BPA.  If this is the case, it may be helpful to identify the socio-economic categories of the awardees in the 18F Agile Blanket Purchase Agreement Ordering Guide.

**Comment by jposi** [comment]
18F currently plans to make each task order under the BPA open to all BPA awardees. If there is a deviation from this, the RFQ will clearly indicate whether the order is being set aside for a specific socio-economic status.
