### ISSUE TITLE
Reason for No Quote

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#19]
In the Request for Quotation (RFQ), the government requests a "brief explanation as to the reason for “No Quote”."  Would the government mind sharing what this information will be used for and if there are any reasons for No Quote that would be looked upon unfavorably.  For example, small businesses may have the bandwidth to respond to a limited number of RFQs.  During "high season" for some agencies, small businesses may be inundated with RFPs/RFQs.

**Comment by randyhart** [comment]
There are many reasons not to quote. Pursuant to section 7.0 of the BPA, vendors are required to "submit a response on all task order request for quotes" and, if a vendor chooses not to bid, to provide a brief explanation as to the reason. 18F intends to use the data to help it make better procurement decisions in the current and future orders. Additionally, failure "to consistently provide a response to task order RFQs" may be a basis for off-ramping.
