### ISSUE TITLE
Key Personnel statements are contradictory

### ISSUE THREAD

**Issue by davecassidytcg** [18F/bpa-fedramp-dashboard#20]
Section 5.7.2.a states "All contractor employees assigned to perform this task order will be Key Personnel" while 5.7.2.f states "At a minimum, a Project Manager must be identified and designated as Key Personnel." The latter statement seems to contradict the former.

**Comment by jposi** [comment]
Thanks for the comment. All employees must be identified as key personnel, and at least one employee shall be a product manager or delivery manager. The RFQ will be corrected to reflect that change.

**Comment by patrickmcconnell** [comment]
@jposi this may be very burdensome on small businesses to provide all personnel as key personnel up front.  This essentially means that we need to have 5 people on the bench not dedicated to other projects at the exact same time when the RFQ comes out and we don't dedicate them to a project until after award.  Having 5 people on the bench is extremely risky for small businesses considering the competition for these opportunities and the fact that the project itself is only 2 months long.  I propose revising this to:
- Select one or two roles for which we must propose key resources as part of our staffing plan
- Require that all personnel be key upon award such that they cannot be swapped off of the project without prior approval
I'd be happy to discuss further if you have questions on my concerns.

**Comment by adamjhorvath** [comment]
Regardless of business size, the key personnel requirements appear overly stringent.  We have a similar comment that only a few roles should be considered key as opposed to all roles when procurement timelines are so short, especially when the government requests firm fixed price that will still require delivery by the vendor and acceptance by the government anyway.  Especially when typical engagements are 2-4 months long and the procurement lifecycle could take 2-4 weeks or longer (as much as 25-50% of the project implementation duration).

**Comment by jposi** [comment]
Based on vendor feedback we are going to revise the key personnel clause in the final RFQ.
