### ISSUE TITLE
Indicate set-aside status

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#21]
In Agile BPA RFQs, it would be very helpful for vendors if the government could indicate towards the beginning of each RFQ whether it is set aside for a specific socio-economic status or open to all awardees.  Thank you!

**Comment by randyhart** [comment]
18F currently plans to make each task order under the BPA open to all BPA awardees. If there is a deviation from this, the RFQ will clearly indicate whether the order is being set aside for a specific socio-economic status category.
