### ISSUE TITLE
Publishing in Transparency Policy

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#22]
In the Transparency Policy, I assume that our proposal text will not be published.  Would it be possible for the government to add a clause specific to this?

**Comment by randyhart** [comment]
Yes.  To address this question, we will update the policy to include the following sentence: "Unless otherwise explicitly stated in the Request for Quotation, vendors' proposals will *not* be publicly available, subject to applicable laws and regulations"

**Comment by randyhart** [comment]
@patrickmcconnell I'm going to re-open this one just to make sure we update the policy language.  Thanks!
