### ISSUE TITLE
Invoicing for FedRAMP

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#24]
In the Performance Work Statement, it states that invoicing is to be performed monthly, but there is only a single CLIN to be delivered at the end of month.  Is it possible to propose monthly invoicing for partial completion or some mid-project deliverable?  Monthly invoicing greatly aids small businesses, though once every two months is not too burdensome either.  Would the government mind clarifying whether they are expecting two invoices or one invoice total for FedRAMP?

**Comment by randyhart** [comment]
The CLIN structure in the draft RFQ was meant to authorize monthly invoicing. Please note that the quantity is for 2 and unit is for months.
