### ISSUE TITLE
FedRAMP data format and sample data

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-fedramp-dashboard#26]
We are unable to locate the data format and sample data referenced in the FedRAMP SOW:

A template of the data format of the data can be found in this Github Repository and sample data is available here.

Will that be provided prior to official release of the RFQ?  This will be very helpful in our pricing strategy.  

It will also be helpful to know the maximum number of rows expected in the CSV file to determine whether there are performance or other constraints for a static site.  

Please also confirm whether the data is a single CSV file with a flat data structure, multiple CSV files with cross-references, or a single CSV file with internal cross-references.

**Comment by jposi** [comment]
A sample CSV is available [here](https://github.com/18F/fedramp-micropurchase/blob/master/P-ATO.csv) and the full CSV will be provided before the RFQ is released.
