### ISSUE TITLE
Questions for Pre-Solicitation # ID09160019

### ISSUE THREAD

**Issue by mnieters** [18F/bpa-fedramp-dashboard#29]
Please review the attached regarding our questions for the above mentioned RFQ.  Thank you!
[18F FedRamp questions.docx](https://github.com/18F/bpa-fedramp-dashboard/files/176333/18F.FedRamp.questions.docx)

**Comment by randyhart** [comment]
@mnieters thank you for the questions.  Would you mind breaking each question into a separate GitHub "Issue"?  It'll be a great help to our team that is tracking and responding to questions.  Thanks!

**Comment by mnieters** [comment]
@randyhart I would be more than happy to break these out and apologize for not seeing this sooner.  Will you still be able to accept the questions if I am able to submit them separately at this time?  Please advise ASAP.  Thank you!

**Comment by jposi** [comment]
Yes, we will be able to accept the questions. We agreed to that on our call at 1:30 PM EST.
