### ISSUE TITLE
User Accounts/Access Control

### ISSUE THREAD

**Issue by sjfischr** [18F/bpa-fedramp-dashboard#32]
There is a mention of a number of different groups that would need access to the FedRAMP private information.  Does the dashboard need to support user accounts and different access to data?  If so, how will user accounts be managed?  Does 18F have a centralized user administration / authorization solution that needs to be integrated with FedRAMP dashboard?

**Comment by jposi** [comment]
User authentication is *not* necessary. Although there are different user groups, no private FedRAMP data is included in this requirement.
