### ISSUE TITLE
Training Requirements

### ISSUE THREAD

**Issue by sjfischr** [18F/bpa-fedramp-dashboard#34]
Has the COR determined the appropriate level of training?  Will that be conducted after the 2 month development effort?

**Comment by randyhart** [comment]
The training provisions included in the PWS will be removed. In lieu of training, 18F intends to include the following requirement: "Additionally, Government requires that the contractor will generate comprehensive and complete documentation, both within the code itself, within the source code version control system (e.g., through proper use of descriptive commit messages, issue tracking, pull requests, etc.), and as appropriate, in separate documentation, provide artifacts, and create new user stories based on the sprint."
