### ISSUE TITLE
User Stories and Acceptance Criteria

### ISSUE THREAD

**Issue by sjfischr** [18F/bpa-fedramp-dashboard#35]
Who is responsible for writing the user stories and the acceptance criteria? Will this be done by the Government Product Owner, or the vendor?

**Comment by BlakeNewman** [comment]
@sjfischr Wouldn't that normally be done by the entire team including client, vendor, and product owner?

**Comment by jposi** [comment]
User stories should be the product of collaboration. That said, the product owner has ultimate responsibility for the backlog and ensuring that acceptance criteria are set forth for user stories before the sprint commences.
