### ISSUE TITLE
Teaming Arrangement Question

### ISSUE THREAD

**Issue by JeffreyDanforth** [18F/bpa-fedramp-dashboard#38]
The draft RFQ states that copies of teaming arrangements are required as part of the submission and that they will count against the 15 page limitation for the technical response. This may be an issue as teaming agreements are typically multiple pages.

**Comment by adamjhorvath** [comment]
Adding a related comment/clarification request: Please confirm that the government is only requesting copies of Contract Teaming Arrangements (CTA) if they are formed for this opportunity and not teaming agreements with potential subcontractors.

**Comment by jposi** [comment]
GSA will not require teaming arrangements to be included as part of the technical quotation. Vendors will be asked to provide copies of finalized teaming arrangements after award. The PWS will be revised to reflect this.

@adamjhorvath we will respond to your question shortly.

**Comment by randyhart** [comment]
In accordance with Section 14 of the BPA, CTAs may only be formed with current Agile BPA holders; CTAs with non-BPA holders are not allowed. However, subcontracting arrangements will be allowed for this order. Refer to the following link on more information regarding the difference between CTAs and subcontractor arrangements: http://www.gsa.gov/portal/category/100647.  Vendors will be asked to provide copies of finalized teaming/subcontractor arrangements after award. The PWS and RFQ will be revised to reflect this.
