### ISSUE TITLE
Project related communication tools

### ISSUE THREAD

**Issue by JeffreyDanforth** [18F/bpa-fedramp-dashboard#40]
Section 6.11 of the current PWS:  Does GSA envision all project-related correspondence between the winning bidder and the 18F client to be through the AASBS?  Please provide more detailed information regarding the use of the portal and whether this will be the required communication medium on future task order projects. Alternatively, will e-mail be an acceptable means of communication for this project-related communication?

**Comment by jposi** [comment]
No, correspondence between the awardee and Government does not need to be through AASBS. As outlined in Section 6.11 of the PWS, the contractor shall use the portal to upload status reports, deliverables, invoices. Email will be an acceptable means of communication for project-related communication. Vendor may also be asked to use Slack or other internal communication tools with 18F.
