### ISSUE TITLE
Site Organization and Technology Selection

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-fedramp-dashboard#43]
1. Does the FedRAMP customer want all the additional content and design that would be included in a stand-alone site such as introductory content, about page, contact forms, etc. or do they just want the report pages from a report selection list?  

2. Should the site be built with a generic look-and-feel for integration into another site, or should we develop a more “finished product” look and feel for a stand-alone site?

3. If the content will integrate with another site, does the customer (or 18F) have a specific preference for Javascript and CSS frameworks?

**Comment by jposi** [comment]
1. No, the Government's requirement is for a dashboard. 

2+3. As stated in the Section 4.0 of the PWS, the Contractor shall use US Web Design Standards. Further design decisions will be made post award.
