### ISSUE TITLE
Correction of Defect Timelines

### ISSUE THREAD

**Issue by bothanus** [18F/bpa-fedramp-dashboard#46]
The QASP procedures states that "The Contractor must correct the defect(s) within the timeframes established in the PWS”. Can the government clarify what are the timeframes for the correction of defects established in the PWS?

**Comment by jposi** [comment]
Any user stories that are not accepted must be completed in the next sprint, unless the product owner and 18F product manager agree to move it to a later sprint. The QASP will be revised to reflect this.
