### ISSUE TITLE
QASP - Source control

### ISSUE THREAD

**Issue by fmorelli** [18F/bpa-fedramp-dashboard#48]
Should the table in the QASP document specify that the code be in source control? Also deployed to staging should be known (tagged) version from source baseline.

**Comment by jposi** [comment]
This is an excellent suggestion. We do require in the PWS the deliverable of a "[v]ersion controlled open source repository of code that comprises dashboard." However, the QASP will be amended to reflect version control requirements. With regard to git flow, however, 18F is not committed to a particular git flow.
