### ISSUE TITLE
Roles & Responsibilities

### ISSUE THREAD

**Issue by fmorelli** [18F/bpa-fedramp-dashboard#51]
For each role, can the Government Roles & Responsibilities document identify from which agency the role will typically be fulfilled? Some are 18F, others likely from originating agency.

**Comment by randyhart** [comment]
For this requirement, all government employees will be GSA employees. The Contracting Office (including the CO and Procurement Project Manager) are with FAS Region 9. The Product Owner is with the FedRAMP program office. All other employees are with 18F. All of these roles should fall within the same organization with the exception of the Product Owner which may vary from order to order.
