### ISSUE TITLE
Third-party libraries

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-fedramp-dashboard#54]
Section 4.0, Requirements of the PWS. Is the use of third-party libraries allowed, in addition to the US Web Design Standards? Is there an approved list of third-party libraries including versions?

**Comment by jposi** [comment]
Yes. Third party libraries are allowed. There is no pre-existing list of approved third-party libraries, however, section 6.10 of the PWS provides that "[t]he contractor shall use open source technologies wherever possible, in support of the 18F Source Code Policy. All licenses must be expressly listed in the deliverable."
