### ISSUE TITLE
Calendar vs. business days

### ISSUE THREAD

**Issue by fmorelli** [18F/bpa-fedramp-dashboard#56]
Section 6.2, Period of Performance of the RFQ states “The period performance for this task order is delivery of the final product 60 days after the Post Award Conference. The Period of Performance begins on the date of the Post Award Conference and ends 60 days after the Post Award Conference.”  Are these business days or calendar days?

**Comment by jposi** [comment]
Calendar days. The PWS will be revised to reflect this.
