### ISSUE TITLE
Static site

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-fedramp-dashboard#59]
Section 4.0, Requirements of the PWS. What is the definition of a “static site”?  It appears that the page will update dynamically with a json/csv from GitHub. It also appears to have potentially dynamic user interaction.To clarify, is the requirement that all files are stored statically (server-side) and all dynamic interaction is enabled in the browser (client-side)?

**Comment by jposi** [comment]
Yes, all data files will be stored statically and accessed via client-side requests.
