### ISSUE TITLE
Possible missing Eval and Award procedures

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-fedramp-dashboard#60]
Section 3, Procedures for Task Order Awards of the Ordering Guide has three main steps: Task Planning; Competition; and Evaluation and Award. There are no procedures provided for the Evaluation and Award step. Can you please provide this?

**Comment by jposi** [comment]
Individual RFQs issued against the BPA will include evaluation information based on whatever acquisition techniques are used for each order. We will clarify the ordering guide to be consistent with this response.

**Comment by randyhart** [comment]
This was resolved by @MCHopson - see issue #61
