### ISSUE TITLE
Possible missing competition steps

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-fedramp-dashboard#61]
Section 3, Competition of the Ordering Guide appears to be missing formatting for the competition steps.The intent appears to be an ordered list. See the first sentence in Section 3 that ends with “...that will consist of the following steps:”.

**Comment by jposi** [comment]
@MCHopson can you please review this.

**Comment by MCHopson** [comment]
@jposi Yes, I just revised two things to the ordering guide. First, updated the company name from InQbation to Agileana.  Second, added bullets to the referenced section that made it seem like something was missing from Section 3 - Competition of the ordering guide.
