### ISSUE TITLE
Code Repository as a Deliverable

### ISSUE THREAD

**Issue by fmorelli** [18F/bpa-fedramp-dashboard#64]
The QASP includes the testing of code as a deliverable but not a code repository. Should the QASP also include a public Git repo which complies with the 18F Open Source Policy as a Deliverable or Required Service?

**Comment by jposi** [comment]
We do require in the PWS the deliverable of a "[v]ersion controlled open source repository of code that comprises dashboard." However, the QASP will be amended to reflect version control requirements.
