### ISSUE TITLE
Similar Experience Requirement

### ISSUE THREAD

**Issue by sbedns** [18F/bpa-fedramp-dashboard#67]
Would GSA consider front-end dashboards that are not public, but private dashboards that belong to GSA an example of similar experience? If so, would GSA consider screen shots of the dashboards, instead of providing links and software code?

d. Similar Experience. The offeror shall provide short summaries of two (2) front-end dashboards that have been delivered for previous clients. The summaries shall describe what frameworks and libraries were used in building the dashboard and why they best suited the user story. The projects must have been delivered by either a) the Offeror, b) a teaming partner that is proposed in response to this RFQ, and/or c) a key personnel that is being proposed in response to this RFQ. In the project summary, please identify how the offeror’s team was involved in the development. The summary shall include links to the public Git repository that includes the source code that was developed and accepted for the project. The summary should also include live links of the final product or current staging environment. If live links are not available, screenshots can be provided, along with a brief explanation as to why the project is no longer live.

**Comment by jposi** [comment]
Previously answered in issue #11
