### ISSUE TITLE
Tech Quote: Technical Approach or just Staffing Approach

### ISSUE THREAD

**Issue by adamjhorvath** [18F/bpa-fedramp-dashboard#70]
The government states in the RFQ 7. Quotation Instructions:
"Technical Quotation. The Government intends to utilize oral presentations for this procurement. Therefore, aspects of your written technical quotation shall only include the information outlined below:" and provides a list of items that specifically exclude the technical approach. 

The technical approach is a very important element to outlining a vendor's understanding of the RFQ and would seem to be very relevant for assessment.

Can the government confirm that they do not wish to be presented with a written technical approach other than as it pertains strictly to staffing in any written section?

**Comment by jposi** [comment]
Yes.  Confirmed. The Government will ask questions pertaining to Offeror's technical approach as part of the Interview-Style Oral Presentation.
