### ISSUE TITLE
Inspection and Acceptance 

### ISSUE THREAD

**Issue by adamjhorvath** [18F/bpa-fedramp-dashboard#72]
We suggest the government define the “reasonable” inspection and acceptance period as 10 business days.  A clearly defined inspection and acceptance period is a necessary piece of a project delivery schedule.

**Comment by jposi** [comment]
18F will clarify that inspection and acceptance shall occur no later than 10 business days after the conclusion of a sprint. The PWS will be revised to reflect this.
