### ISSUE TITLE
Vencore 18F Questions and Comments

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#73]
[Vencore Services and Solutions, Inc. 18F Questions and Comments.docx](https://github.com/18F/bpa-fedramp-dashboard/files/177198/Vencore.Services.and.Solutions.Inc.18F.Questions.and.Comments.docx)

**Comment by vzvenyach** [comment]
Hi @vencoreinc thanks for these questions. Would you mind breaking each question into a separate GitHub "Issue"? It'll be a great help to our team that is tracking and responding to questions. Thanks!

**Comment by patrickmcconnell** [comment]
> Given the short nature of the task order period of performance and the team size requirements, the fifteen (15) page technical proposal and oral requirements are extensive and not in line with the requirements of the BPA proposal, or in the spirit of “show don’t tell”.  We believe this will limit effective competition as the investment to respond is not in line with the resulting work required.  Vencore suggests that a much smaller and lightweight response that leverages the technologies described.

We agree with this comment.  A 15 page response for a 2 month project does not align with other page counts and durations in other agencies.

**Comment by jposi** [comment]
Closing this comment as the comments were re-posted as single issues.
