### ISSUE TITLE
Draft PWS Section 5.5.1 Transition Plan – Item # 3 

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#74]
The government states that the vendor will be responsible to coordinate with the COR and potentially another vendor, and implement the Transition Plan according to the COR’s direction. Is it expected that the execution of the Transition Plan will occur during the sixty (60) day period of performance?  If not, how is this expected to be funded and for what period?  Vencore recommends an optional Time and Materials (T&M) CLIN to support execution of the plan or additional post-delivery support if needed.

**Comment by jposi** [comment]
Thank you for this suggestion. Right now we expect that the code will be transitioned during the period of performance. Agile development practices would suggest that the agency's development team would be involved throughout the development, and so a transition need not be particularly complex.
