### ISSUE TITLE
Draft PWS Section 5.6.3 System Documentation and Training

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#76]
Will the government elaborate on what is considered appropriate, effective and essential for training?  Given the Firm Fixed Price (FFP) nature of this task order, this could be widely interpreted.  Vencore recommends specific expectations be set for training documentation to ensure consistent results from offerors.  Alternatively, include a Time and Materials (T&M) CLIN for any requirement in excess of what could be reasonably performed by the proposed staffing.

**Comment by jposi** [comment]
Please see Issue #34.
