### ISSUE TITLE
Instructions for Oral Presentations - Participants 

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#78]
The government states the contractor can include as many participants as it feels necessary and that “All proposed Key Personnel currently employed by the offeror or its teaming partners shall attend the session.”  Please see question 4 regarding the requirements for Key Personnel.  Vencore recommends that not all personnel on the team be considered key and expected to attend.  This will allow the flexibility of the contractor to include more expertise for certain tasks, such as environment configuration, without requiring them to otherwise materially participate.

**Comment by jposi** [comment]
See #20 about modifications to key personnel.
