### ISSUE TITLE
Draft PWS Section 7.1 Content of Invoice 

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#79]
What is the expectation with regards to the total amount monthly invoice for Firm Fixed Price (FFP) task orders?  Vencore recommends either based equal monthly payments and/or the pro-rated appropriate amount.  Alternatively, the task order could be invoiced at the completion of each sprint cycle.

**Comment by jposi** [comment]
Please see Issue #24
