### ISSUE TITLE
Government Roles and Responsibilities 

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#80]
What is the expectation for participation of 18F and Product Owner in the Agile Development Cycle?  Will they materially participate in Agile ceremonies such as sprint planning, definition of done, daily stand-up, retrospectives, etc. or will the contractor Project Manager be expected to proxy for government participation and confirm decisions, provide action items and provide summaries of activities?  Vencore recommends the government fully participate in the team and have access to the management tools used by the team.  At a minimum, we suggest the level of participation be defined.

**Comment by jposi** [comment]
Please refer to our response to Issue #35
