### ISSUE TITLE
Draft PWS Section 3.0 Scope 

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#81]
The scope is to deliver the public beta launch of the FedRAMP Dashboard.  Please elaborate on the process for public launch.  Does this include security testing, IV+V as any other processes in access of the deliverables described in the PWS?  Is the launch expected to be included in the sixty (60) day period of performance, which may require at least one (1) sprint to be dedicated to launch activities?  Vencore recommends that the government clarify where the responsibility of this task order ends as related to “launch.”

**Comment by jposi** [comment]
Launch would involve supporting any transition of the code to 18F & the FedRAMP team. If the other requirements are met - that the system works with the data provided, that it is deployable with a single bash command - the 18F and FedRAMP team will have what they need to launch the site. No IV&V is expected.
