### ISSUE TITLE
RFQ Question

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#82]
Given the short nature of the task order period of performance and the team size requirements, the fifteen (15) page technical proposal and oral requirements are extensive and not in line with the requirements of the BPA proposal, or in the spirit of “show don’t tell”.  We believe this will limit effective competition as the investment to respond is not in line with the resulting work required.  Vencore suggests that a much smaller and lightweight response that leverages the technologies described.
	For example – 
-	A Technical Response or Letter of Intent to bid include company information and OCI clauses; or
-	Past performance citations limited to one (1) page in total with either link to site uploaded to the GitHub repository or design artifacts provided on AAS; or
-	Staffing and approach provided at orals or staffing approach limited to one (1) page with supporting resumes in a standard format.  Ideally, a completely orals based selection approach.  Proposed team participates and describes the staffing approach, past experience and approach for this task order.

**Comment by randyhart** [comment]
The page requirements are a maximum limit, not a requirement of pages that must be filled.
