### ISSUE TITLE
Ordering Guide Section 2 Authorized Users & Points of Contact 

### ISSUE THREAD

**Issue by vencoreinc** [18F/bpa-fedramp-dashboard#83]
The government states use of this BPA is exclusively for 18F and its own work on internal projects and for value-added services for 18F partner agencies.  Can the government provide a list of agencies that can currently procure through the 18F BPA?

**Comment by randyhart** [comment]
Any federal agency can work with 18F to access the Agile BPA. 18F's intake team receives requests from many Government agencies seeking assistance with digital procurements.  Partner agencies will be added as partners for the Agile BPA after Interagency Agreements are signed and the scope is determined to align with the Agile BPA.
