### ISSUE TITLE
Similar experience

### ISSUE THREAD

**Issue by ksternjr** [18F/bpa-fedramp-dashboard#84]
WWT Asynchrony Labs uses open source tools on most of our projects and those are driven by customer solutions/requirements For previous government work , the source code is/was secured and monitored on their internal private network.   For our commercial work, the source code is owned by our clients and we are under NDA not to disclose or share without their written permission.   In some cases we can provide a link to the front page, but without login and passwords 18F would not be able to maneuver past the splash page.  All source code that is developed by WWTAL is owned by our customers, and therefore we will not be able to provide 18F with a public git respository.  Once we start projects with 18F if it is your desire to have everything public facing in Github, we will honor that and disclose links as requested.
Will 18F reconsider this requirement – once we start projects with 18F if it is your and your customers desire to have everything on public facing Github we will honor that and disclose links as requested, however if you will not provide relief from this requirement for the Fedramp opportunity, we will not be compliant and therefore not submit a competitive bid.

**Comment by randyhart** [comment]
Please see Issue #11
